# Generated by Django 5.2.1 on 2025-06-03 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cgst_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='freight_applicable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='freight_charge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst_applicable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst_rate_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst_source_of_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_of_duty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sgst_percent',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='igst_applicable',
        ),
        migrations.RemoveField(
            model_name='voucherproductitem',
            name='movement_type',
        ),
        migrations.AddField(
            model_name='voucher',
            name='movement_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('job_work', 'Job Work')], default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voucherproductitem',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucherproductitem',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='voucherproductitem',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Buyer_Voucher', 'Buyer Voucher'), ('Seller_Voucher', 'Seller Voucher'), ('Job_Work_Voucher', 'Job Work Voucher'), ('Quotation', 'Quotation'), ('Delivery_Challan', 'Delivery Challan')], max_length=20),
        ),
    ]
